language: java
jdk:
- openjdk8
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
env:
  global:
  - secure: WvvNvknDnFrqQc9Dd/yDXvmE/C7nv++0UD+x5RwgyDOAVNqbKb9+hE458o7iO5GqcDn7t+xpqpCVmtl/I+ddAe3Mrju1LZ9wV+M3g3xMgKJRfn1Ny6g5JRIayoWp3BChFRIBRkA20CN7PeMyc2X81yBD8MY6gJWElUAg+JHWJhM=
  - secure: LmNKk2cYzePjGZU8rkURiqvlUbJnL3zpQZZRIUzjGwx577H4VVr9CNNSm8zYnN+HOPn5HjQvaNovv3yi4ijbUaUaxPa5ZFho67HAhm6jzOMuk/oAFnELFacle02trkQYIlXAdG0Vj7RMBmfQ1WpIoxfAuGUcToSUFeqP2Skzspk=
  - secure: s5ZJFQNozCsrFY2KTUuabi1HxsCniO5DbjV76/ham2UshONKzIqXkMlF/d6MPbiqdaHuT0Le6kwRMQiIauQes1b755sKcBBxDK1l1DX6P6aMxvKhtc7cO0f+xvGDpkP6hfLhKqpKT1XmeTW8DOaeCevQc62XgGWfSG/SfooEyNw=
  - secure: pmAEB7RQmD9eseKrfV8veMHgfqZP2b10Rz0qBOEcl+g/1fV/Zhav4ePdww2XhDBKGx7vKb10luJjrodchsAoDTbAppMgHc4f8dMctQB4Bd0JLogY2O6NuU+4P/aG26zrKb18rUPlpuWMLDsAPTY/HkPQP00P1CGaqSgrYRO4Nx4=
cache:
  directories:
  - $HOME/.gradle/caches
